### ISSUE TITLE
403 Adyen::PermissionError...

### ISSUE THREAD

**Issue by taylorbrooks** [adyen-examples/adyen-rails-online-payments#1]
Hey there!

First off, thanks for building this example application -- it's been really helpful to see how it interacts with the Adyen API.

I'm not sure if this is the best medium for support or if I should contact support, but I'm getting an error when hitting `localhost:8080/checkout/dropin`.

```ruby
raise Adyen::PermissionError.new("Missing user permissions; https://docs.adyen.com/user-management/user-roles", request_data)
```

From what I can tell, I've properly setup the API_KEY, MERCHANT_ACCOUNT, and ORIGIN_KEY AND my user has the correct permissions and roles (see below).
![image](https://user-images.githubusercontent.com/117657/77277504-0e09d200-6c8b-11ea-908a-167852a30e6b.png)

Any ideas on what could be causing the 403?

**Comment by taylorbrooks** [comment]
@hbkwong :)

**Comment by mwlalata** [comment]
why is this closed without providing solutions ?

**Comment by axelb152** [comment]
Bumping this thread, as I have the same problem and don't see a solution. I have a `ADYEN_API_KEY`, `ADYEN_CLIENT_KEY` and `ADYEN_HMAC_KEY` already setup, but I still run into this user permissions error.
