### ISSUE TITLE
Set redirectUrl using hostname

### ISSUE THREAD

**Issue by gcatanese** [adyen-examples/adyen-rails-online-payments#22]
The redirectUrl is hardcoded `http://localhost:8080` therefore it doesn't work when the app is deployed on Gitpod (or other cloud providers). Refactor to use the hostname header.

**Comment by jillingk** [comment]
#25 see pull request. Also changed gitpod to install newer version of ruby.

**Comment by gcatanese** [comment]
Fixed by #25
