### ISSUE TITLE
some requests can be cached - it would be nice to add an example of that 

### ISSUE THREAD

**Issue by dkuku** [adyen-examples/adyen-rails-online-payments#39]
Some requests can be cached - it would be nice to add an example of that.
Maybe even implement cache in the library would make sense ?

**Comment by jlengrand** [comment]
Hey there, apologies for the delay in the response. 

I do agree that some requests could be cached. However that example is mainly meant to let merchants see an example of integration that is as plain as possible and I feel like caching would add complexity that has not much to do with Adyen. Do you disagree?

**Comment by jlengrand** [comment]
Closing because inactive. Feel free to reopen if there are good reasons :)
