### ISSUE TITLE
checkout.rb calls incomplete method path for adyen_client

### ISSUE THREAD

**Issue by tokyodaruma** [adyen-examples/adyen-rails-online-payments#58]
**Problem:**

Initiating a drop-in session returns a `NoMethodError` due to the following code under checkout.rb:
`response = adyen_client.checkout.sessions(req)`

Reviewing the [adyen-ruby-api-library](https://github.com/Adyen/adyen-ruby-api-library) gem reveals that there is another path needed in between checkout and sessions called: "payments_api".

**Solution:**
`response = adyen_client.checkout.payments_api.sessions(req)`

I'll submit a pull request shortly.

**Comment by gcatanese** [comment]
@tokyodaruma Thanks for spotting the error and submitting the PR. We are investigating an error when running the app on Gitpod, once solved we should be able to merge it.

**Comment by Kwok-he-Chu** [comment]
Closed in:
https://github.com/adyen-examples/adyen-rails-online-payments/pull/59 and https://github.com/adyen-examples/adyen-rails-online-payments/pull/63
