### ISSUE TITLE
NameError: validationItem not used in checkout.rb

### ISSUE THREAD

**Issue by tokyodaruma** [adyen-examples/adyen-rails-online-payments#60]
`notification = notifications.first()["NotificationRequestItem"]` is set but not used again. 

`notification` should be used in place of `validationItem` otherwise a `NameError` is thrown on `validationItem` since it was not previously set.

current:
```
if validator.valid_notification_hmac?(validationItem, hmacKey)
  puts validationItem["eventCode"]
  puts validationItem["merchantReference"]
  "[accepted]"
else
```

solution:
```
if validator.valid_notification_hmac?(notification, hmacKey)
  puts notification["eventCode"]
  puts notification["merchantReference"]
  "[accepted]"
else
```

Submitting new PR shortly.

**Comment by Kwok-he-Chu** [comment]
Thank you for you contribution and PR @tokyodaruma I'll have a look at it this week

**Comment by Kwok-he-Chu** [comment]
Closed in https://github.com/adyen-examples/adyen-rails-online-payments/pull/61/files
